name: Deploy

on:
  push:
    branches: [ master ]

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-24.04-arm # generally faster than x86 to start
    steps:
    - uses: actions/checkout@v5.0.0
    - uses: cachix/install-nix-action@v31.7.0
    - run: nix build .#resume
    - uses: actions/deploy-pages@v4.0.5
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: .
        publish_branch: gh-pages
