name: Deploy

on:
  push:
    branches: [ master ]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-24.04-arm
    steps:
    - uses: actions/checkout@v5.0.0
    - uses: cachix/install-nix-action@v31.7.0
    - run: |
        nix build
        cp result resume.pdf
    - uses: actions/upload-pages-artifact@v4.0.0
      with:
        path: |
          index.html
          resume.pdf
    - uses: actions/deploy-pages@v4.0.5
